# Generated by Django 5.2.17 on 2026-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='calibration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='competency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='misconceptions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='quality_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='quality_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='role_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='style',
            field=models.CharField(blank=True, default='explain', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='track',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
