# Generated by Django 5.2.17 on 2026-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_accommodation_preferences_user_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='clarification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='selection_reason',
            field=models.JSONField(default=dict),
        ),
    ]
