# Generated by Django 5.2.17 on 2026-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_privacyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='ratebucket',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
