# Generated by Django 5.2.17 on 2026-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attempt_submitted_at_alter_interview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('organization', 'catalog_key'), name='unique_organization_catalog_key'),
        ),
    ]
